---
title: "Data wrangling"
author: "sandra huang"
date: "10/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# using palmer penguin data set for example
library(palmerpenguins)
```

## check penguin data set
```{r}
head(penguins, 5)
```

## select function -> generate new data set
```{r}
penguins %>%
  select(species, bill_length_mm, body_mass_g, flipper_length_mm)

#also can use minus to remove the column
penguins %>%
  select(-species, -bill_length_mm, -body_mass_g)
```

## filter -> extract a subset of rows
```{r}
penguins %>%
  filter(species == 'Adelie' & body_mass_g > 2000)
```

## create and renaming columns
```{r}
penguins %>%
  mutate(flipper_bill_ration = flipper_length_mm/bill_length_mm)

penguins %>%
  rename(b_l_m = bill_length_mm, b_d_m = bill_depth_mm, f_l_m = flipper_length_mm)
```

## sorting the rows
```{r}
penguins %>% 
  arrange(desc(bill_length_mm))
```

## summarizing the data
```{r}
penguins %>%
  group_by(species) %>%
  summarise(
    num_rows = n(),
    avg_weight_kg = mean(body_mass_g/1000, na.rm = TRUE)
  )
```

## column wise -> compute sth across column
```{r}
penguins %>%
  summarise(
    across(everything(), ~sum(is.na(.x)))
  )

penguins %>%
  summarise(
    across(where(is.numeric), ~mean(.x, na.rm = TRUE))
  )
```

## join multiple data frames
```{r}
species <- unique(penguins$species)
latin_name <- c('Pygoscelis Adelie', 'Pygoscelis papua', 'Pygoscelis antarcticus')
latin_name_df <- data.frame(species, latin_name)

penguins %>%
  inner_join(latin_name_df)

```